<?php 

$lista_ubicaciones_api = array(
//array(1 ,"Montevideo" , 0 , "Sin Especificar"),
array(1 ,"Montevideo" , 1 , "Aguada"),
array(1 ,"Montevideo" , 2 , "Aires Puros"),
array(1 ,"Montevideo" , 3 , "Arroyo Seco"),
array(1 ,"Montevideo" , 4 , "Atahualpa"),
array(1 ,"Montevideo" , 5 , "B. De Carrasco"),
array(1 ,"Montevideo" , 6 , "Bella Vista"),
array(1 ,"Montevideo" , 7 , "Belvedere"),
array(1 ,"Montevideo" , 8 , "Bolivar"),
array(1 ,"Montevideo" , 9 , "Brazo Oriental"),
array(1 ,"Montevideo" , 10 , "Buceo"),
array(1 ,"Montevideo" , 11 , "Cno. Carrasco"),
array(1 ,"Montevideo" , 12 , "Cno. Maldonado"),
array(1 ,"Montevideo" , 13 , "Capurro"),
array(1 ,"Montevideo" , 14 , "Carrasco"),
array(1 ,"Montevideo" , 15 , "Casabó"),
array(1 ,"Montevideo" , 16 , "Centro"),
array(1 ,"Montevideo" , 17 , "Cerrito"),
array(1 ,"Montevideo" , 18 , "Cerro"),
array(1 ,"Montevideo" , 19 , "Ciudad Vieja"),
array(1 ,"Montevideo" , 20 , "Colón"),
array(1 ,"Montevideo" , 21 , "Cordón"),
array(1 ,"Montevideo" , 22 , "Goes"),
array(1 ,"Montevideo" , 23 , "Jacinto Vera"),
array(1 ,"Montevideo" , 24 , "La Blanqueada"),
array(1 ,"Montevideo" , 25 , "La Comercial"),
array(1 ,"Montevideo" , 26 , "La Figurita"),
array(1 ,"Montevideo" , 27 , "La Teja"),
array(1 ,"Montevideo" , 28 , "Lezica"),
array(1 ,"Montevideo" , 29 , "Malvín"),
array(1 ,"Montevideo" , 30 , "Malvín Norte"),
array(1 ,"Montevideo" , 31 , "Manga"),
array(1 ,"Montevideo" , 32 , "Maroñas"),
array(1 ,"Montevideo" , 33 , "Nuevo Paris"),
array(1 ,"Montevideo" , 34 , "Palermo"),
array(1 ,"Montevideo" , 35 , "Parque Batlle"),
array(1 ,"Montevideo" , 36 , "Parque Rodó"),
array(1 ,"Montevideo" , 37 , "Paso De La Arena"),
array(1 ,"Montevideo" , 38 , "Paso Molino"),
array(1 ,"Montevideo" , 39 , "Peñarol"),
array(1 ,"Montevideo" , 40 , "Piedras Blancas"),
array(1 ,"Montevideo" , 41 , "Pocitos"),
array(1 ,"Montevideo" , 42 , "Pocitos Nuevo"),
array(1 ,"Montevideo" , 43 , "Prado"),
array(1 ,"Montevideo" , 44 , "Punta Carretas"),
array(1 ,"Montevideo" , 45 , "Punta Gorda"),
array(1 ,"Montevideo" , 46 , "Punta Rieles"),
array(1 ,"Montevideo" , 47 , "Reducto"),
array(1 ,"Montevideo" , 48 , "Sayago"),
array(1 ,"Montevideo" , 49 , "Tres Cruces"),
array(1 ,"Montevideo" , 50 , "Unión"),
array(1 ,"Montevideo" , 51 , "Villa Biarritz"),
array(1 ,"Montevideo" , 52 , "Villa Dolores"),
array(1 ,"Montevideo" , 53 , "Villa Española"),
array(1 ,"Montevideo" , 54 , "Villa Muñoz"),
array(1 ,"Montevideo" , 55 , "Pajas Blancas"),
array(1 ,"Montevideo" , 60 , "Apartamentos Con Muebles"),
array(1 ,"Montevideo" , 61 , "Puerto Buceo"),
array(1 ,"Montevideo" , 62 , "Marconi"),
array(1 ,"Montevideo" , 63 , "Golf"),
array(1 ,"Montevideo" , 64 , "Las Acacias"),
array(1 ,"Montevideo" , 65 , "J. Hipodromo"),
array(1 ,"Montevideo" , 66 , "Maroñas Curva"),
array(1 ,"Montevideo" , 67 , "Paso Carrasco"),
array(1 ,"Montevideo" , 68 , "Carrasco Norte"),
array(1 ,"Montevideo" , 69 , "Parque Miramar"),
array(1 ,"Montevideo" , 70 , "Barra Santa Lucia"),
array(1 ,"Montevideo" , 71 , "Melilla"),
array(1 ,"Montevideo" , 72 , "Nuevo Centro"),
array(1 ,"Montevideo" , 73 , "Larrañaga"),
array(1 ,"Montevideo" , 999 , "Otros"),
array(2 ,"Artigas" , 1 , "Artigas"),
array(2 ,"Artigas" , 2 , "Bella Unión"),
array(2 ,"Artigas" , 3 , "Baltasar Brum"),
array(2 ,"Artigas" , 4 , "Tomás Gomensoro"),
array(2 ,"Artigas" , 5 , "Javier De Viana"),
array(2 ,"Artigas" , 6 , "Las Piedras"),
array(2 ,"Artigas" , 7 , "Mataojito"),
array(2 ,"Artigas" , 8 , "Menezes"),
array(2 ,"Artigas" , 9 , "Mones Quintela"),
array(2 ,"Artigas" , 10 , "Palma Sola"),
array(2 ,"Artigas" , 11 , "Paso Farías"),
array(2 ,"Artigas" , 12 , "Pintadito"),
array(2 ,"Artigas" , 13 , "Pje. Carumbé"),
array(2 ,"Artigas" , 14 , "Pje. Diego Lamas"),
array(2 ,"Artigas" , 16 , "Pje. Paso Campamento"),
array(2 ,"Artigas" , 17 , "Pueblo Sequeira"),
array(2 ,"Artigas" , 18 , "Sarandí Del Arapey"),
array(2 ,"Artigas" , 20 , "Topador"),
array(2 ,"Artigas" , 999 , "Otra"),
array(3 ,"Canelones" , 1 , "Araminda"),
array(3 ,"Canelones" , 2 , "Atlantida"),
array(3 ,"Canelones" , 3 , "Canelones"),
array(3 ,"Canelones" , 4 , "El Pinar"),
array(3 ,"Canelones" , 5 , "Empalme Olmos"),
array(3 ,"Canelones" , 6 , "La Paz"),
array(3 ,"Canelones" , 7 , "Lagomar"),
array(3 ,"Canelones" , 8 , "Las Piedras"),
array(3 ,"Canelones" , 9 , "Los Cerrillos"),
array(3 ,"Canelones" , 10 , "Marindia"),
array(3 ,"Canelones" , 11 , "Medanos De Solymar"),
array(3 ,"Canelones" , 12 , "Migues"),
array(3 ,"Canelones" , 13 , "Pando"),
array(3 ,"Canelones" , 14 , "Parque Del Plata"),
array(3 ,"Canelones" , 15 , "Pinamar"),
array(3 ,"Canelones" , 16 , "Progreso"),
array(3 ,"Canelones" , 17 , "Salinas"),
array(3 ,"Canelones" , 18 , "San Jacinto"),
array(3 ,"Canelones" , 19 , "San José De Carrasco"),
array(3 ,"Canelones" , 20 , "San Ramon"),
array(3 ,"Canelones" , 21 , "Santa Lucia"),
array(3 ,"Canelones" , 22 , "Santa Rosa"),
array(3 ,"Canelones" , 23 , "Sauce"),
array(3 ,"Canelones" , 24 , "Shangrila"),
array(3 ,"Canelones" , 25 , "Solymar"),
array(3 ,"Canelones" , 26 , "Tala"),
array(3 ,"Canelones" , 27 , "Toledo"),
array(3 ,"Canelones" , 28 , "Neptunia"),
array(3 ,"Canelones" , 29 , "Balneario Argentino"),
array(3 ,"Canelones" , 30 , "Costa Azul"),
array(3 ,"Canelones" , 31 , "Cuchilla Alta"),
array(3 ,"Canelones" , 32 , "Jaureguiberry"),
array(3 ,"Canelones" , 33 , "El Bosque"),
array(3 ,"Canelones" , 34 , "Fortin De Santa Rosa"),
array(3 ,"Canelones" , 35 , "La Floresta"),
array(3 ,"Canelones" , 36 , "La Tuna"),
array(3 ,"Canelones" , 37 , "Los Titanes"),
array(3 ,"Canelones" , 38 , "Santa Ana"),
array(3 ,"Canelones" , 39 , "Santa Lucía Del Este"),
array(3 ,"Canelones" , 40 , "Villa Argentina"),
array(3 ,"Canelones" , 41 , "Montes De Solymar"),
array(3 ,"Canelones" , 42 , "Parque De Solymar"),
array(3 ,"Canelones" , 43 , "Pinares De Solymar"),
array(3 ,"Canelones" , 44 , "Colinas De Solymar"),
array(3 ,"Canelones" , 45 , "Barra De Carrasco"),
array(3 ,"Canelones" , 46 , "Bello Horizonte"),
array(3 ,"Canelones" , 47 , "Guazú-virá"),
array(3 ,"Canelones" , 48 , "Las Toscas"),
array(3 ,"Canelones" , 49 , "Lomas De Solymar"),
array(3 ,"Canelones" , 50 , "San Luis"),
array(3 ,"Canelones" , 51 , "San Cristóbal"),
array(3 ,"Canelones" , 52 , "El Colorado"),
array(3 ,"Canelones" , 53 , "Juanicó"),
array(3 ,"Canelones" , 54 , "Aguas Corrientes"),
array(3 ,"Canelones" , 55 , "Barros Blancos"),
array(3 ,"Canelones" , 56 , "Ciudad De La Costa"),
array(3 ,"Canelones" , 57 , "Colonia Nicolich"),
array(3 ,"Canelones" , 58 , "Joaquín Suárez"),
array(3 ,"Canelones" , 59 , "Paso Carrasco"),
array(3 ,"Canelones" , 60 , "San Antonio"),
array(3 ,"Canelones" , 61 , "Soca"),
array(3 ,"Canelones" , 62 , "Bañado De Medina"),
array(3 ,"Canelones" , 63 , "Biarritz"),
array(3 ,"Canelones" , 64 , "Cerrillos"),
array(3 ,"Canelones" , 65 , "El Dorado"),
array(3 ,"Canelones" , 66 , "Estación Pedrera"),
array(3 ,"Canelones" , 67 , "Juan Antonio Artigas"),
array(3 ,"Canelones" , 68 , "Las Vegas"),
array(3 ,"Canelones" , 69 , "Mata Siete"),
array(3 ,"Canelones" , 70 , "Piedras De Afilar"),
array(3 ,"Canelones" , 71 , "Pueblo Suizo"),
array(3 ,"Canelones" , 72 , "San Bautista"),
array(3 ,"Canelones" , 73 , "Santa Teresita"),
array(3 ,"Canelones" , 74 , "Sierra Del Mar"),
array(3 ,"Canelones" , 75 , "Solís Chico"),
array(3 ,"Canelones" , 76 , "Suárez"),
array(3 ,"Canelones" , 77 , "Totoral"),
array(3 ,"Canelones" , 78 , "Villa Aeroparque"),
array(3 ,"Canelones" , 79 , "Villa Crespo"),
array(3 ,"Canelones" , 80 , "Villa Felicidad"),
array(3 ,"Canelones" , 81 , "Villa San José"),
array(3 ,"Canelones" , 82 , "Vista Linda"),
array(3 ,"Canelones" , 83 , "La Tahona"),
array(3 ,"Canelones" , 999 , "Otra"),
array(4 ,"Cerro Largo" , 1 , "Melo"),
array(4 ,"Cerro Largo" , 2 , "Rio Branco"),
array(4 ,"Cerro Largo" , 3 , "Fraile Muerto"),
array(4 ,"Cerro Largo" , 4 , "Lago Merín"),
array(4 ,"Cerro Largo" , 5 , "Tupambaé"),
array(4 ,"Cerro Largo" , 999 , "Otra"),
array(5 ,"Colonia" , 1 , "Colonia"),
array(5 ,"Colonia" , 2 , "Juan Lacaze"),
array(5 ,"Colonia" , 3 , "Nueva Palmira"),
array(5 ,"Colonia" , 4 , "Tarariras"),
array(5 ,"Colonia" , 5 , "Carmelo"),
array(5 ,"Colonia" , 6 , "Rosario"),
array(5 ,"Colonia" , 7 , "Colonia Suiza"),
array(5 ,"Colonia" , 8 , "Laguna De Los Patos"),
array(5 ,"Colonia" , 9 , "Florencio Sanchez"),
array(5 ,"Colonia" , 10 , "Nueva Helvecia"),
array(5 ,"Colonia" , 11 , "Campana"),
array(5 ,"Colonia" , 12 , "Valdense"),
array(5 ,"Colonia" , 999 , "Otra"),
array(6 ,"Durazno" , 1 , "Durazno"),
array(6 ,"Durazno" , 2 , "Sarandí Del Yi"),
array(6 ,"Durazno" , 3 , "Villa Del Carmen"),
array(6 ,"Durazno" , 4 , "Cerro Chato"),
array(6 ,"Durazno" , 999 , "Otra"),
array(7 ,"Flores" , 1 , "Trinidad"),
array(7 ,"Flores" , 2 , "Ismael Cortinas"),
array(7 ,"Flores" , 3 , "Andresito"),
array(7 ,"Flores" , 4 , "La Casilla"),
array(7 ,"Flores" , 999 , "Otra"),
array(8 ,"Florida" , 1 , "Florida"),
array(8 ,"Florida" , 2 , "Fray Marcos"),
array(8 ,"Florida" , 3 , "Sarandi Grande"),
array(8 ,"Florida" , 4 , "Casupá"),
array(8 ,"Florida" , 5 , "Veinticinco De Mayo"),
array(8 ,"Florida" , 999 , "Otra"),
array(9 ,"Lavalleja" , 1 , "José Pedro Varela"),
array(9 ,"Lavalleja" , 2 , "Minas"),
array(9 ,"Lavalleja" , 3 , "Solís De Mataojo"),
array(9 ,"Lavalleja" , 4 , "Villa Serrana"),
array(9 ,"Lavalleja" , 5 , "Aguas Blancas"),
array(9 ,"Lavalleja" , 6 , "José Batlle Y Ordoñez"),
array(9 ,"Lavalleja" , 7 , "Polanco"),
array(9 ,"Lavalleja" , 999 , "Otra"),
array(10 ,"Maldonado" , 1 , "Maldonado"),
array(10 ,"Maldonado" , 2 , "Piriapolis"),
array(10 ,"Maldonado" , 3 , "Punta Del Este"),
array(10 ,"Maldonado" , 4 , "José Ignacio"),
array(10 ,"Maldonado" , 5 , "La Barra"),
array(10 ,"Maldonado" , 6 , "Las Flores"),
array(10 ,"Maldonado" , 7 , "Bella Vista"),
array(10 ,"Maldonado" , 8 , "Playa Hermosa"),
array(10 ,"Maldonado" , 9 , "Playa Verde"),
array(10 ,"Maldonado" , 10 , "Manantiales"),
array(10 ,"Maldonado" , 11 , "Portezuelo"),
array(10 ,"Maldonado" , 12 , "Sauce De Portezuelo"),
array(10 ,"Maldonado" , 13 , "Solis"),
array(10 ,"Maldonado" , 14 , "Pan De Azucar"),
array(10 ,"Maldonado" , 15 , "Aiguá"),
array(10 ,"Maldonado" , 16 , "Garzón"),
array(10 ,"Maldonado" , 17 , "San Carlos"),
array(10 ,"Maldonado" , 18 , "Solís Grande"),
array(10 ,"Maldonado" , 19 , "Abra De Perdomo"),
array(10 ,"Maldonado" , 20 , "Cerro Pelado"),
array(10 ,"Maldonado" , 21 , "Cerros Azules"),
array(10 ,"Maldonado" , 22 , "Gregorio Aznárez"),
array(10 ,"Maldonado" , 23 , "Hipódromo"),
array(10 ,"Maldonado" , 24 , "Punta Ballena"),
array(10 ,"Maldonado" , 25 , "Punta Colorada"),
array(10 ,"Maldonado" , 26 , "Pinares"),
array(10 ,"Maldonado" , 27 , "Playa Grande"),
array(10 ,"Maldonado" , 28 , "Pueblo Edén"),
array(10 ,"Maldonado" , 29 , "Punta Fría"),
array(10 ,"Maldonado" , 30 , "Punta Piedras"),
array(10 ,"Maldonado" , 31 , "San Rafael"),
array(10 ,"Maldonado" , 32 , "Punta Negra"),
array(10 ,"Maldonado" , 999 , "Otra"),
array(11 ,"Paysandú" , 1 , "Paysandu"),
array(11 ,"Paysandu" , 2 , "Guichón"),
array(11 ,"Paysandu" , 3 , "Quebracho"),
array(11 ,"Paysandu" , 4 , "Porvenir"),
array(11 ,"Paysandu" , 999 , "Otra"),
array(12 ,"Rio Negro" , 1 , "Fray Bentos"),
array(12 ,"Rio Negro" , 2 , "Young"),
array(12 ,"Rio Negro" , 3 , "Nuevo Berlín"),
array(12 ,"Rio Negro" , 4 , "San Javier"),
array(12 ,"Rio Negro" , 999 , "Otra"),
array(13 ,"Rivera" , 1 , "Rivera"),
array(13 ,"Rivera" , 2 , "Tranqueras"),
array(13 ,"Rivera" , 3 , "Vichadero"),
array(13 ,"Rivera" , 4 , "Minas De Corrales"),
array(13 ,"Rivera" , 999 , "Otra"),
array(14 ,"Rocha" , 1 , "Castillos"),
array(14 ,"Rocha" , 2 , "Rocha"),
array(14 ,"Rocha" , 3 , "La Pedrera"),
array(14 ,"Rocha" , 4 , "Barra De Valizas"),
array(14 ,"Rocha" , 5 , "Aguas Dulces"),
array(14 ,"Rocha" , 6 , "Barra Del Chuy"),
array(14 ,"Rocha" , 7 , "Cabo Polonio"),
array(14 ,"Rocha" , 8 , "Costa Azul"),
array(14 ,"Rocha" , 9 , "La Coronilla"),
array(14 ,"Rocha" , 10 , "La Paloma"),
array(14 ,"Rocha" , 11 , "Punta Del Diablo"),
array(14 ,"Rocha" , 12 , "Las Garzas"),
array(14 ,"Rocha" , 13 , "El Palmar"),
array(14 ,"Rocha" , 14 , "La Esmeralda"),
array(14 ,"Rocha" , 15 , "Arachania"),
array(14 ,"Rocha" , 16 , "Chuy"),
array(14 ,"Rocha" , 17 , "Lascano"),
array(14 ,"Rocha" , 18 , "La Palma"),
array(14 ,"Rocha" , 19 , "Santa Teresa"),
array(14 ,"Rocha" , 20 , "Velázquez"),
array(14 ,"Rocha" , 999 , "Otra"),
array(15 ,"Salto" , 1 , "Salto"),
array(15 ,"Salto" , 2 , "Belén"),
array(15 ,"Salto" , 3 , "Colonia Lavalleja"),
array(15 ,"Salto" , 4 , "Mataojo"),
array(15 ,"Salto" , 5 , "Rincón De Valentín"),
array(15 ,"Salto" , 6 , "San Antonio"),
array(15 ,"Salto" , 7 , "Villa Constitución"),
array(15 ,"Salto" , 999 , "Otra"),
array(16 ,"San José" , 1 , "Ecilda Paullier"),
array(16 ,"San José" , 2 , "Libertad"),
array(16 ,"San José" , 3 , "Playa Pascual"),
array(16 ,"San José" , 4 , "San José"),
array(16 ,"San José" , 5 , "Villa Rodriguez"),
array(16 ,"San José" , 6 , "Ciudad Del Plata"),
array(16 ,"San José" , 7 , "Arroyo De La Virgen"),
array(16 ,"San José" , 8 , "Balneario Kiyú"),
array(16 ,"San José" , 9 , "Carreta Quemada"),
array(16 ,"San José" , 10 , "Colonia Agraria Delta"),
array(16 ,"San José" , 11 , "Mal Abrigo"),
array(16 ,"San José" , 12 , "Rafael Perazza"),
array(16 ,"San José" , 13 , "Tropas Viejas"),
array(16 ,"San José" , 999 , "Otra"),
array(17 ,"Soriano" , 1 , "Cardona"),
array(17 ,"Soriano" , 2 , "Dolores"),
array(17 ,"Soriano" , 3 , "Mercedes"),
array(17 ,"Soriano" , 4 , "Coquimbo"),
array(17 ,"Soriano" , 5 , "Risso"),
array(17 ,"Soriano" , 6 , "Santa Catalina"),
array(17 ,"Soriano" , 7 , "Villa Soriano"),
array(17 ,"Soriano" , 999 , "Otra"),
array(18 ,"Tacuarembó" , 1 , "Paso De Los Toros"),
array(18 ,"Tacuarembó" , 2 , "San Gregorio De Polanco"),
array(18 ,"Tacuarembó" , 3 , "Tacuarembó"),
array(18 ,"Tacuarembó" , 4 , "Pueblo Centenario"),
array(18 ,"Tacuarembó" , 999 , "Otra"),
array(19 ,"Treinta Y Tres" , 1 , "Treinta Y Tres"),
array(19 ,"Treinta Y Tres" , 2 , "Santa Clara Del Olimar"),
array(19 ,"Treinta Y Tres" , 3 , "Vergara"),
array(19 ,"Treinta Y Tres" , 999 , "Otra"),
array(999 ,"Sin Especificar" , 999 , "Otra")
);
/*
foreach($lista_ubicaciones_api as $lista_ubicaciones){
	echo 'array('.$lista_ubicaciones[0].' ,"'.ucwords(mb_strtolower($lista_ubicaciones[1],'UTF-8')).'" , '.$lista_ubicaciones[2].' , "'.ucwords(mb_strtolower($lista_ubicaciones[3],'UTF-8')).'"),<br>';
}*/

?>