<?php 
// Lista ubicación:
$lista_ubicaciones = array(
	array("Montevideo",		"Unión",						1),	
	array("Montevideo",		"Tres cruces",					1),
	array("Montevideo",		"Prado",						1),
	array("Montevideo",		"Villa Biarritz",				1),
	array("Montevideo",		"Punta carretas",				1),
	array("Montevideo",		"Puerto de buceo",				1),
	array("Montevideo",		"Pocitos",						1),
	array("Montevideo",		"Punta Gorda",					1),
	array("Montevideo",		"Paso Carrasco",				1),
	array("Montevideo",		"Parque Rodó",					1),
	array("Montevideo",		"Parque Batlle",				1),
	array("Montevideo",		"Peñarol",						1),
	array("Montevideo",		"Malvín",						1),
	array("Montevideo",		"La Blanqueada",				1),
	array("Montevideo",		"Golf",							1),
	array("Montevideo",		"Cordón",						1),
	array("Montevideo",		"Colón",						1),
	array("Montevideo",		"Jacinto Vera",					1),
	array("Montevideo",		"Goes",							1),
	array("Montevideo",		"Carrasco",						1),
	array("Montevideo",		"Buceo",						1),
	array("Montevideo",		"Carrasco Este",				0),
	array("Montevideo",		"Biarritz",						0),
	array("Montevideo",		"Ciudad vieja",					1),
	array("Montevideo",		"Centro",						1),
	array("Montevideo",		"La Comercial",					1),
	array("Montevideo",		"Atahualpa/Prado",				1),
	array("Montevideo",		"Athaualpa",					1),
	array("Montevideo",		"Barra de Carrasco",			1),
	array("Montevideo",		"Aguada",						1),
	array("Montevideo",		"Arroyo Seco",					1),
	array("Montevideo",		"Reducto",						1),
	array("Montevideo",		"Sin especificar",				1),
	array("Canelones",		"Ciudad de la Costa",			1),
	array("Canelones",		"Costa de Oro",					1),
	array("Canelones",		"Rural",						1),
	array("Canelones",		"Atlántida",					1),
	array("Canelones",		"Balneario Argentino",			1),
	array("Canelones",		"Barra de Carrasco",			1),
	array("Canelones",		"Bello Horizonte",				1),
	array("Canelones",		"Canelones",					1),
	array("Canelones",		"Ciudad de la Costa",			0),
	array("Canelones",		"Colinas de Solymar",			1),
	array("Canelones",		"Costa Azul",					1),
	array("Canelones",		"Cuchilla Alta",				1),
	array("Canelones",		"El Bosque",					1),
	array("Canelones",		"El Pinar",						1),
	array("Canelones",		"Empalme Olmos",				1),
	array("Canelones",		"Fortín de Santa Rosa",			1),
	array("Canelones",		"Guazú Virá",					1),
	array("Canelones",		"Jaureguiberry",				1),
	array("Canelones",		"La Floresta",					1),
	array("Canelones",		"La Paz",						1),
	array("Canelones",		"La Tuna",						1),
	array("Canelones",		"Lagomar",						1),
	array("Canelones",		"Las Piedras",					1),
	array("Canelones",		"Las Toscas",					1),
	array("Canelones",		"Lomas de Solymar",				1),
	array("Canelones",		"Los Cerrillos",				1),
	array("Canelones",		"Los Titanes",					1),
	array("Canelones",		"Marindia",						1),
	array("Canelones",		"Médanos de Solymar",			1),
	array("Canelones",		"Migues",						1),
	array("Canelones",		"Montes de Solymar",			1),
	array("Canelones",		"Neptunia",						1),
	array("Canelones",		"Pando",						1),
	array("Canelones",		"Parque de Solymar",			1),
	array("Canelones",		"Parque del Plata",				1),
	array("Canelones",		"Pinamar",						1),
	array("Canelones",		"Pinares de Solymar",			1),
	array("Canelones",		"Progreso",						1),
	array("Canelones",		"Salinas",						1),
	array("Canelones",		"San Antonio (Uyca)",			1),
	array("Canelones",		"San José de Carrasco",			1),
	array("Canelones",		"San Cristóbal",				1),
	array("Canelones",		"San Jacinto",					1),
	array("Canelones",		"San Luis",						1),
	array("Canelones",		"San Ramón",					1),
	array("Canelones",		"Santa Ana",					1),
	array("Canelones",		"Santa Lucía",					1),
	array("Canelones",		"Santa Lucía del Este",			1),
	array("Canelones",		"Santa Rosa",					1),
	array("Canelones",		"Sauce",						1),
	array("Canelones",		"Shangrilá",					1),
	array("Canelones",		"Solymar",						1),
	array("Canelones",		"Tala",							1),
	array("Canelones",		"Toledo",						1),
	array("Canelones",		"Villa Argentina",				1),
	array("Canelones",		"Barrios Privados",				1),
	array("Canelones",		"Sin especificar",				1),
	array("Maldonado",		"Punta del Este",				1),
	array("Maldonado",		"Gregorio Aznares",				1),
	array("Maldonado",		"Pan de Azucar",				1),
	array("Maldonado",		"Piriápolis",					1),
	array("Maldonado",		"Beaulieu",						0),
	array("Maldonado",		"Bella Vista",					1),
	array("Maldonado",		"Centro",						1),
	array("Maldonado",		"Cerro del Toro",				1),
	array("Maldonado",		"Cerro San Antonio",			1),
	array("Maldonado",		"Fuente Venus",					1),
	array("Maldonado",		"Los Ángeles",					1),
	array("Maldonado",		"Playa Grande",					1),
	array("Maldonado",		"Punta Fría",					1),
	array("Maldonado",		"Rinconada",					1),
	array("Maldonado",		"Barrio Country",				1),
	array("Maldonado",		"Barrio la Falda",				1),
	array("Maldonado",		"Beaullieu",					1),
	array("Maldonado",		"Castillo de Piria",			1),
	array("Maldonado",		"La Cascada",					1),
	array("Maldonado",		"La Gloria",					1),
	array("Maldonado",		"Piriapolis Centro Comercial",	1),
	array("Maldonado",		"Zona Hotel Argentino",			1),
	array("Maldonado",		"Punta Colorada",				1),
	array("Maldonado",		"Las Flores",					1),
	array("Maldonado",		"Playa Hermosa",				1),
	array("Maldonado",		"Playa Verde",					1),
	array("Maldonado",		"Proa del Mar",					1),
	array("Maldonado",		"Punta Negra",					1),
	array("Maldonado",		"San Francisco",				1),
	array("Maldonado",		"Solís",						1),
	array("Maldonado",		"Solanas",						1),
	array("Maldonado",		"Portezuelo",					1),
	array("Maldonado",		"Lagunas del Diario",			1),
	array("Maldonado",		"Punta Ballena",				1),
	array("Maldonado",		"Bahia del Pinar",				1),
	array("Maldonado",		"Chihuahua",					1),
	array("Maldonado",		"Club del Lago",				1),
	array("Maldonado",		"El Pejerrey",					1),
	array("Maldonado",		"La Pataia",					1),
	array("Maldonado",		"Laguna del Diario",			1),
	array("Maldonado",		"Laguna del Sauce",				1),
	array("Maldonado",		"Las Cumbres",					1),
	array("Maldonado",		"Ocean Park",					1),
	array("Maldonado",		"Playa las Grutas",				1),
	array("Maldonado",		"Portezuelo Bosque",			1),
	array("Maldonado",		"Punta del Chileno",			1),
	array("Maldonado",		"Rinconada Alta",				1),
	array("Maldonado",		"Santa Hilda",					1),
	array("Maldonado",		"Sauce de Portezuelo",			1),
	array("Maldonado",		"Tio Tom",						1),
	array("Maldonado",		"Aidy Grill",					1),
	array("Maldonado",		"Arcobaleno",					1),
	array("Maldonado",		"Barrio Córdoba",				1),
	array("Maldonado",		"Beverly Hills",				1),
	array("Maldonado",		"Cantegril",					1),
	array("Maldonado",		"Golf",							1),
	array("Maldonado",		"Las Delicias",					1),
	array("Maldonado",		"Península",					1),
	array("Maldonado",		"Pinares",						1),
	array("Maldonado",		"Playa Brava",					1),
	array("Maldonado",		"Playa Mansa",					1),
	array("Maldonado",		"Puerto",						1),
	array("Maldonado",		"Punta Shopping",				1),
	array("Maldonado",		"Rincón del Indio",				1),
	array("Maldonado",		"Roosevelt",					1),
	array("Maldonado",		"San Rafael",					1),
	array("Maldonado",		"Playa Mansa Las Delicias",		1),
	array("Maldonado",		"Playa Mansa Pinares",			1),
	array("Maldonado",		"Zona El Golf",					1),
	array("Maldonado",		"Zona Roosevelt",				1),
	array("Maldonado",		"La Barra",						1),
	array("Maldonado",		"La Pastora",					1),
	array("Maldonado",		"Lugano",						1),
	array("Maldonado",		"Manantiales",					1),
	array("Maldonado",		"Montoya",						1),
	array("Maldonado",		"Punta Piedras",				1),
	array("Maldonado",		"Balneario Buenos Aires",		1),
	array("Maldonado",		"Arenas de José Ignacio",		1),
	array("Maldonado",		"Edén Rock",					1),
	array("Maldonado",		"El Caracol Costa Bonita",		1),
	array("Maldonado",		"Estrella de Mar",				1),
	array("Maldonado",		"La Juanita",					1),
	array("Maldonado",		"Laguna de Jose Ignacio",		1),
	array("Maldonado",		"Laguna Garzón",				1),
	array("Maldonado",		"Las Garzas",					1),
	array("Maldonado",		"Pueblo Garzón",				1),	
	array("Maldonado",		"San Sebastián",				1),
	array("Maldonado",		"San Vicente",					1),
	array("Maldonado",		"Santa Isabel",					1),
	array("Maldonado",		"Santa Monica",					1),
	array("Maldonado",		"Santa Rita",					1),
	array("Maldonado",		"Las Garzas",					1),
	array("Maldonado",		"Laguna Garzón",				1),
	array("Maldonado",		"Aigua",						1),
	array("Maldonado",		"Maldonado",					1),
	array("Maldonado",		"San Carlos",					1),
	array("Maldonado",		"Sin especificar",				1),
	array("Artigas",		"Artigas",						1),
	array("Artigas",		"Baltasar Brum",				1),
	array("Artigas",		"Bella Unión",					1),
	array("Artigas",		"Bernabé Rivera",				1),
	array("Artigas",		"Cuaro",						1),
	array("Artigas",		"Javier de Viana",				1),
	array("Artigas",		"Pintadito",					1),
	array("Artigas",		"Tomás Gomensoro",				1),
	array("Artigas",		"Topador",						1),
	array("Artigas",		"Sin especificar",				1),
	array("Cerro Largo",	"Aceguá",						1),
	array("Cerro Largo",	"Cerro de las Cuentas",			1),
	array("Cerro Largo",	"Fraile Muerto",				1),
	array("Cerro Largo",	"Isidoro Noblía",				1),
	array("Cerro Largo",	"Melo",							1),
	array("Cerro Largo",	"Río Branco",					1),
	array("Cerro Largo",	"Tres Islas",					1),
	array("Cerro Largo",	"Sin especificar",				1),
	array("Colonia",		"Arrivillaga",					1),
	array("Colonia",		"Artilleros",					1),
	array("Colonia",		"Barker",						1),
	array("Colonia",		"Blanca Arena",					1),
	array("Colonia",		"Boca del Rosario",				1),
	array("Colonia",		"Brisas del Plata",				1),
	array("Colonia",		"Carmelo",						1),
	array("Colonia",		"Cerros de San Juan",			1),
	array("Colonia",		"Colonia Cosmopolita",			1),
	array("Colonia",		"Colonia del Sacramnto",		1),
	array("Colonia",		"Colonia Miguelete",			1),
	array("Colonia",		"Colonia Valdense",				1),
	array("Colonia",		"Conchillas",					1),
	array("Colonia",		"Cufré",						1),
	array("Colonia",		"El semillero",					1),
	array("Colonia",		"El Solado",					0),
	array("Colonia",		"Estanzuela",					1),
	array("Colonia",		"Juan Lacaze",					1),
	array("Colonia",		"La Paz (Uyco)",				1),
	array("Colonia",		"Los Pinos",					1),
	array("Colonia",		"Nueva Helvecia",				1),
	array("Colonia",		"Nueva Palmira",				1),
	array("Colonia",		"Ombúes de Lavalle",			1),
	array("Colonia",		"Paraje Minuano",				1),
	array("Colonia",		"Paso Minuano",					1),
	array("Colonia",		"Paso Antolín",					1),
	array("Colonia",		"Pastoreo",						1),
	array("Colonia",		"Playa Azul",					1),
	array("Colonia",		"Playa Britópolis",				1),
	array("Colonia",		"Playa Parant",					1),
	array("Colonia",		"Puerto Inglés",				1),
	array("Colonia",		"Rosario",						1),
	array("Colonia",		"Santa Regina",					1),
	array("Colonia",		"Tarariras",					1),
	array("Colonia",		"Sin especificar",				1),
	array("Durazno",		"Durazno",						1),
	array("Durazno",		"San Jorge",					1),
	array("Durazno",		"Santa Bernardita",				1),
	array("Durazno",		"Sin especificar",				1),
	array("Flores",			"San Gregorio Carrio",			1),
	array("Flores",			"Trinidad",						1),
	array("Flores",			"Sin especificar",				1),
	array("Florida",		"25 de agosto",					1),
	array("Florida",		"Cardal",						1),
	array("Florida",		"Cerro Colorado (FI)",			1),
	array("Florida",		"Florida",						1),
	array("Florida",		"Fray Marcos",					1),
	array("Florida",		"Independencia",				1),
	array("Florida",		"La Cruz",						1),
	array("Florida",		"Pintado",						1),
	array("Florida",		"Sarandí Grande",				1),
	array("Florida",		"Sin especificar",				1),
	array("Lavalleja",		"Colón",						1),
	array("Lavalleja",		"Illescas",						1),
	array("Lavalleja",		"José Pedro Varela",			1),
	array("Lavalleja",		"La Mariscala",					1),
	array("Treinta y Tres",	"María Albina",					1),
	array("Lavalleja",		"Minas",						1),
	array("Lavalleja",		"Piraraja",						1),
	array("Lavalleja",		"Solís de Mataojo",				1),
	array("Lavalleja",		"Zapican",						1),
	array("Lavalleja",		"Sin especificar",				1),
	array("Paysandú",		"Chapicuy",						1),
	array("Paysandú",		"Guaviyú",						1),
	array("Paysandú",		"Paysandú",						1),
	array("Paysandú",		"Piedra Sola",					1),
	array("Paysandú",		"Quebracho",					1),
	array("Paysandú",		"Sin especificar",				1),
	array("Río Negro",		"Algorta",						1),
	array("Río Negro",		"Andresito",					1),
	array("Río Negro",		"Barrio Anglo",					1),
	array("Río Negro",		"Cardozo",						1),
	array("Río Negro",		"Carlos Reyles",				1),
	array("Río Negro",		"Fray Bentos",					1),
	array("Río Negro",		"General Borges",				1),
	array("Río Negro",		"Grecco",						1),
	array("Río Negro",		"Las Cañas",					1),
	array("Río Negro",		"Nuevo Berlín",					1),
	array("Río Negro",		"Pueblo Orgoroso",				1),
	array("Río Negro",		"Rincón del Bonete",			1),
	array("Río Negro",		"San Javier",					1),
	array("Río Negro",		"Villa María",					1),
	array("Río Negro",		"Young",						1),
	array("Río Negro",		"Sin especificar",				1),
	array("Rivera",			"La Pedrera (Rv)",				1),
	array("Rivera",			"Laguñón",						1),
	array("Rivera",			"Lagos del Norte",				1),
	array("Rivera",			"Mandubí",						1),
	array("Rivera",			"Masoller",						1),
	array("Rivera",			"Minas de Corrales",			1),
	array("Rivera",			"Paso Campamento",				1),
	array("Rivera",			"Rivera",						1),
	array("Rivera",			"Santa Teresa",					1),
	array("Rivera",			"Traqueras",					1),
	array("Rivera",			"Sin especificar",				1),
	array("Rocha",			"Centro",						1),
	array("Rocha",			"Playa de la Viuda",			1),
	array("Rocha",			"Playa del Rivero",				1),
	array("Rocha",			"Zona el Bosque",				1),
	array("Rocha",			"Zona Terminal",				1),
	array("Rocha",			"Punta del Diablo",				1),
	array("Rocha",			"Punta Rubia",					1),
	array("Rocha",			"Santa Isabel de la Pedrera",	1),
	array("Rocha",			"Barracas de la Pedrera",		1),
	array("Rocha",			"Centro",						1),
	array("Rocha",			"Diamantes de la Pedrera",		1),
	array("Rocha",			"Playa del Barco",				1),
	array("Rocha",			"Playa Desplayado",				1),
	array("Rocha",			"Pueblo Nuevo",					1),
	array("Rocha",			"San Antonio",					1),
	array("Rocha",			"San Sebastián de la Pedrera",	1),
	array("Rocha",			"Tajamares de la Pedrera",		1),
	array("Rocha",			"Santa María De Rocha",			1),
	array("Rocha",			"Barrio Country",				1),
	array("Rocha",			"Barrio Parque",				1),
	array("Rocha",			"Casco Viejo",					1),
	array("Rocha",			"Centro",						1),
	array("Rocha",			"El Cabito",					1),
	array("Rocha",			"Laguna de Rocha",				1),
	array("Rocha",			"Los Botes",					1),
	array("Rocha",			"Playa Anaconda",				1),
	array("Rocha",			"Playa Bahía",					1),
	array("Rocha",			"Playa la Balconada",			1),
	array("Rocha",			"Playa Serena y Solari",		1),
	array("Rocha",			"Rincón del Rosario",			1),
	array("Rocha",			"Santa María de Rocha",			1),
	array("Rocha",			"La Riviera",					1),
	array("Rocha",			"Antoniópolis",					1),
	array("Rocha",			"Arachania",					1),
	array("Rocha",			"Costa Azul",					1),
	array("Rocha",			"La Aguada",					1),
	array("Rocha",			"Oceanía Del Polonio",			1),
	array("Rocha",			"Cabo",							1),
	array("Rocha",			"Playa la Calavera (Norte)",	1),
	array("Rocha",			"Playa Sur",					1),
	array("Rocha",			"Balneario la Alborada",		1),
	array("Rocha",			"Barra do Chui Brasil",			1),
	array("Rocha",			"Balneario Puimayen",			1),
	array("Rocha",			"Barra del Chuy",				1),
	array("Rocha",			"Chuy",							1),
	array("Rocha",			"Aguas Dulces",					1),
	array("Rocha",			"Barra de Valizas",				1),
	array("Rocha",			"Valizas",						1),
	array("Rocha",			"Castillos",					1),
	array("Rocha",			"Dieciocho de Julio (Ro)",		1),
	array("Rocha",			"Rocha",						1),
	array("Rocha",			"Lascano",						1),
	array("Rocha",			"El Palmar",					1),
	array("Rocha",			"La Esmeralda",					1),
	array("Rocha",			"La Coronilla",					1),
	array("Rocha",			"Sin especificar",				1),
	array("Salto",			"Arenitas Blancas",				1),
	array("Salto",			"Artaux",						1),
	array("Salto",			"Belén",						1),
	array("Salto",			"Colonia   state:de Julio",		1),
	array("Salto",			"Constitución",					1),
	array("Salto",			"Salto",						1),
	array("Salto",			"Termas del Arapey",			1),
	array("Salto",			"Termas del Daymán",			1),
	array("Salto",			"Sin especificar",				1),
	array("San José",		"Boca del Cufré",				1),
	array("San José",		"Delta del Tigre",				1),
	array("San José",		"Ecilda Paullier",				1),
	array("San José",		"Ituzaingó",					1),
	array("San José",		"Libertad",						1),
	array("San José",		"Playa Pascual",				1),
	array("San José",		"San José",						1),
	array("San José",		"San José de Mayo",				1),
	array("San José",		"Scavino",						1),
	array("San José",		"Villa Rodríguez",				1),
	array("San José",		"Sin especificar",				1),
	array("Soriano",		"Canada Nieto",					1),
	array("Soriano",		"Cardona",						1),
	array("Soriano",		"Dolores",						1),
	array("Soriano",		"Egana",						1),
	array("Soriano",		"Florencio Sánchez",			1),
	array("Soriano",		"José Enrique Rodó",			1),
	array("Soriano",		"Mercedes",						1),
	array("Soriano",		"Palmitas",						1),
	array("Soriano",		"Risso",						1),
	array("Soriano",		"Santa Catalina",				1),
	array("Soriano",		"Sin especificar",				1),
	array("Tacuarembó",		"Clara",						1),
	array("Tacuarembó",		"Paso Bonilla",					1),
	array("Tacuarembó",		"Paso de los Toros",			1),
	array("Tacuarembó",		"Paso del Cerro",				1),
	array("Tacuarembó",		"San Gregorio de Polanco",		1),
	array("Tacuarembó",		"Tacuarembó",					1),
	array("Tacuarembó",		"Villa Ansina",					1),
	array("Tacuarembó",		"Sin especificar",				1),
	array("Treinta y Tres",	"Isla Patrulla",				1),
	array("Treinta y Tres",	"Treinta y Tres",				1),
	array("Treinta y Tres",	"Tupambae",						1),
	array("Treinta y Tres",	"Vergara",						1),
	array("Treinta y Tres",	"Sin especificar",				1)
);
?>